// Chinese Text Processor - Segmentation and Pinyin Generation
// Uses pinyin-pro for accurate pinyin with tone marks

import { segment, addDict } from 'pinyin-pro';
import ModernDict from '@pinyin-pro/data/modern';
import type { SegmentedWord, Verse } from '../types';
import type { FHLVerseRecord } from './bibleApi';

// Initialize the modern dictionary for better segmentation
addDict(ModernDict);

// Expanded dictionary with biblical terms and common Chinese words
const WORD_DEFINITIONS: Record<string, { definition: string; partOfSpeech: string }> = {
  // Biblical terms
  '神': { definition: 'God', partOfSpeech: 'noun' },
  '耶穌': { definition: 'Jesus', partOfSpeech: 'noun' },
  '基督': { definition: 'Christ', partOfSpeech: 'noun' },
  '聖靈': { definition: 'Holy Spirit', partOfSpeech: 'noun' },
  '天父': { definition: 'Heavenly Father', partOfSpeech: 'noun' },
  '天國': { definition: 'Kingdom of Heaven', partOfSpeech: 'noun' },
  '天堂': { definition: 'Heaven', partOfSpeech: 'noun' },
  '地獄': { definition: 'Hell', partOfSpeech: 'noun' },
  '福音': { definition: 'Gospel; good news', partOfSpeech: 'noun' },
  '救恩': { definition: 'salvation', partOfSpeech: 'noun' },
  '恩典': { definition: 'grace', partOfSpeech: 'noun' },
  '信心': { definition: 'faith', partOfSpeech: 'noun' },
  '盼望': { definition: 'hope', partOfSpeech: 'noun' },
  '愛': { definition: 'love', partOfSpeech: 'noun/verb' },
  '罪': { definition: 'sin', partOfSpeech: 'noun' },
  '悔改': { definition: 'repentance; to repent', partOfSpeech: 'noun/verb' },
  '饒恕': { definition: 'forgiveness; to forgive', partOfSpeech: 'noun/verb' },
  '永生': { definition: 'eternal life', partOfSpeech: 'noun' },
  '復活': { definition: 'resurrection', partOfSpeech: 'noun' },
  '門徒': { definition: 'disciple', partOfSpeech: 'noun' },
  '使徒': { definition: 'apostle', partOfSpeech: 'noun' },
  '先知': { definition: 'prophet', partOfSpeech: 'noun' },
  '祭司': { definition: 'priest', partOfSpeech: 'noun' },
  '聖殿': { definition: 'temple', partOfSpeech: 'noun' },
  '會堂': { definition: 'synagogue', partOfSpeech: 'noun' },
  '教會': { definition: 'church', partOfSpeech: 'noun' },
  '禱告': { definition: 'prayer; to pray', partOfSpeech: 'noun/verb' },
  '敬拜': { definition: 'worship', partOfSpeech: 'noun/verb' },
  '讚美': { definition: 'praise', partOfSpeech: 'noun/verb' },
  '祝福': { definition: 'blessing; to bless', partOfSpeech: 'noun/verb' },
  '應許': { definition: 'promise', partOfSpeech: 'noun/verb' },
  '約': { definition: 'covenant', partOfSpeech: 'noun' },
  '律法': { definition: 'law (Torah)', partOfSpeech: 'noun' },
  '誡命': { definition: 'commandment', partOfSpeech: 'noun' },
  '公義': { definition: 'righteousness', partOfSpeech: 'noun' },
  '聖潔': { definition: 'holiness; holy', partOfSpeech: 'noun/adjective' },
  '榮耀': { definition: 'glory', partOfSpeech: 'noun' },
  '審判': { definition: 'judgment', partOfSpeech: 'noun' },
  '救贖': { definition: 'redemption', partOfSpeech: 'noun' },
  '十字架': { definition: 'cross', partOfSpeech: 'noun' },
  '寶血': { definition: 'precious blood', partOfSpeech: 'noun' },
  '羔羊': { definition: 'lamb', partOfSpeech: 'noun' },
  '天使': { definition: 'angel', partOfSpeech: 'noun' },
  '魔鬼': { definition: 'devil', partOfSpeech: 'noun' },
  '撒但': { definition: 'Satan', partOfSpeech: 'noun' },
  '有福': { definition: 'blessed', partOfSpeech: 'adjective' },
  '阿們': { definition: 'Amen', partOfSpeech: 'interjection' },
  '哈利路亞': { definition: 'Hallelujah', partOfSpeech: 'interjection' },

  // Biblical names - Old Testament
  '亞伯拉罕': { definition: 'Abraham', partOfSpeech: 'proper noun' },
  '以撒': { definition: 'Isaac', partOfSpeech: 'proper noun' },
  '雅各': { definition: 'Jacob', partOfSpeech: 'proper noun' },
  '猶大': { definition: 'Judah', partOfSpeech: 'proper noun' },
  '大衛': { definition: 'David', partOfSpeech: 'proper noun' },
  '所羅門': { definition: 'Solomon', partOfSpeech: 'proper noun' },
  '摩西': { definition: 'Moses', partOfSpeech: 'proper noun' },
  '亞當': { definition: 'Adam', partOfSpeech: 'proper noun' },
  '夏娃': { definition: 'Eve', partOfSpeech: 'proper noun' },
  '挪亞': { definition: 'Noah', partOfSpeech: 'proper noun' },
  '約瑟': { definition: 'Joseph', partOfSpeech: 'proper noun' },
  '撒母耳': { definition: 'Samuel', partOfSpeech: 'proper noun' },
  '以利亞': { definition: 'Elijah', partOfSpeech: 'proper noun' },
  '以利沙': { definition: 'Elisha', partOfSpeech: 'proper noun' },
  '但以理': { definition: 'Daniel', partOfSpeech: 'proper noun' },
  '以賽亞': { definition: 'Isaiah', partOfSpeech: 'proper noun' },
  '耶利米': { definition: 'Jeremiah', partOfSpeech: 'proper noun' },
  '以西結': { definition: 'Ezekiel', partOfSpeech: 'proper noun' },
  '約伯': { definition: 'Job', partOfSpeech: 'proper noun' },
  '路得': { definition: 'Ruth', partOfSpeech: 'proper noun' },
  '以斯帖': { definition: 'Esther', partOfSpeech: 'proper noun' },
  '撒拉': { definition: 'Sarah', partOfSpeech: 'proper noun' },
  '利百加': { definition: 'Rebecca', partOfSpeech: 'proper noun' },
  '拉結': { definition: 'Rachel', partOfSpeech: 'proper noun' },
  '利亞': { definition: 'Leah', partOfSpeech: 'proper noun' },
  '便雅憫': { definition: 'Benjamin', partOfSpeech: 'proper noun' },
  '法老': { definition: 'Pharaoh', partOfSpeech: 'proper noun' },
  '歌利亞': { definition: 'Goliath', partOfSpeech: 'proper noun' },
  '掃羅': { definition: 'Saul', partOfSpeech: 'proper noun' },
  '約拿': { definition: 'Jonah', partOfSpeech: 'proper noun' },
  '他瑪': { definition: 'Tamar', partOfSpeech: 'proper noun' },
  '波阿斯': { definition: 'Boaz', partOfSpeech: 'proper noun' },
  '俄備得': { definition: 'Obed', partOfSpeech: 'proper noun' },
  '耶西': { definition: 'Jesse', partOfSpeech: 'proper noun' },
  '拿單': { definition: 'Nathan', partOfSpeech: 'proper noun' },
  '羅波安': { definition: 'Rehoboam', partOfSpeech: 'proper noun' },
  '亞比雅': { definition: 'Abijah', partOfSpeech: 'proper noun' },
  '亞撒': { definition: 'Asa', partOfSpeech: 'proper noun' },
  '約沙法': { definition: 'Jehoshaphat', partOfSpeech: 'proper noun' },
  '約蘭': { definition: 'Joram', partOfSpeech: 'proper noun' },
  '烏西雅': { definition: 'Uzziah', partOfSpeech: 'proper noun' },
  '約坦': { definition: 'Jotham', partOfSpeech: 'proper noun' },
  '亞哈斯': { definition: 'Ahaz', partOfSpeech: 'proper noun' },
  '希西家': { definition: 'Hezekiah', partOfSpeech: 'proper noun' },
  '瑪拿西': { definition: 'Manasseh', partOfSpeech: 'proper noun' },
  '亞們': { definition: 'Amon', partOfSpeech: 'proper noun' },
  '約西亞': { definition: 'Josiah', partOfSpeech: 'proper noun' },
  '耶哥尼雅': { definition: 'Jeconiah', partOfSpeech: 'proper noun' },
  '撒拉鐵': { definition: 'Shealtiel', partOfSpeech: 'proper noun' },
  '所羅巴伯': { definition: 'Zerubbabel', partOfSpeech: 'proper noun' },

  // Biblical names - New Testament
  '馬利亞': { definition: 'Mary', partOfSpeech: 'proper noun' },
  '彼得': { definition: 'Peter', partOfSpeech: 'proper noun' },
  '保羅': { definition: 'Paul', partOfSpeech: 'proper noun' },
  '約翰': { definition: 'John', partOfSpeech: 'proper noun' },
  '雅各布': { definition: 'James', partOfSpeech: 'proper noun' },
  '馬太': { definition: 'Matthew', partOfSpeech: 'proper noun' },
  '馬可': { definition: 'Mark', partOfSpeech: 'proper noun' },
  '路加': { definition: 'Luke', partOfSpeech: 'proper noun' },
  '提摩太': { definition: 'Timothy', partOfSpeech: 'proper noun' },
  '提多': { definition: 'Titus', partOfSpeech: 'proper noun' },
  '腓力': { definition: 'Philip', partOfSpeech: 'proper noun' },
  '多馬': { definition: 'Thomas', partOfSpeech: 'proper noun' },
  '巴多羅買': { definition: 'Bartholomew', partOfSpeech: 'proper noun' },
  '安得烈': { definition: 'Andrew', partOfSpeech: 'proper noun' },
  '西門': { definition: 'Simon', partOfSpeech: 'proper noun' },
  '猶達': { definition: 'Judas (Thaddaeus)', partOfSpeech: 'proper noun' },
  '加略人猶大': { definition: 'Judas Iscariot', partOfSpeech: 'proper noun' },
  '施洗約翰': { definition: 'John the Baptist', partOfSpeech: 'proper noun' },
  '尼哥底母': { definition: 'Nicodemus', partOfSpeech: 'proper noun' },
  '拉撒路': { definition: 'Lazarus', partOfSpeech: 'proper noun' },
  '撒該': { definition: 'Zacchaeus', partOfSpeech: 'proper noun' },
  '巴拿巴': { definition: 'Barnabas', partOfSpeech: 'proper noun' },
  '司提反': { definition: 'Stephen', partOfSpeech: 'proper noun' },
  '亞拿尼亞': { definition: 'Ananias', partOfSpeech: 'proper noun' },
  '該亞法': { definition: 'Caiaphas', partOfSpeech: 'proper noun' },
  '彼拉多': { definition: 'Pilate', partOfSpeech: 'proper noun' },
  '希律': { definition: 'Herod', partOfSpeech: 'proper noun' },
  '抹大拉的馬利亞': { definition: 'Mary Magdalene', partOfSpeech: 'proper noun' },
  '馬大': { definition: 'Martha', partOfSpeech: 'proper noun' },

  // Biblical places
  '耶路撒冷': { definition: 'Jerusalem', partOfSpeech: 'proper noun' },
  '伯利恆': { definition: 'Bethlehem', partOfSpeech: 'proper noun' },
  '拿撒勒': { definition: 'Nazareth', partOfSpeech: 'proper noun' },
  '加利利': { definition: 'Galilee', partOfSpeech: 'proper noun' },
  '猶太': { definition: 'Judea', partOfSpeech: 'proper noun' },
  '撒瑪利亞': { definition: 'Samaria', partOfSpeech: 'proper noun' },
  '埃及': { definition: 'Egypt', partOfSpeech: 'proper noun' },
  '以色列': { definition: 'Israel', partOfSpeech: 'proper noun' },
  '巴比倫': { definition: 'Babylon', partOfSpeech: 'proper noun' },
  '迦南': { definition: 'Canaan', partOfSpeech: 'proper noun' },
  '約旦河': { definition: 'Jordan River', partOfSpeech: 'proper noun' },
  '紅海': { definition: 'Red Sea', partOfSpeech: 'proper noun' },
  '西奈山': { definition: 'Mount Sinai', partOfSpeech: 'proper noun' },
  '橄欖山': { definition: 'Mount of Olives', partOfSpeech: 'proper noun' },
  '各各他': { definition: 'Golgotha', partOfSpeech: 'proper noun' },
  '客西馬尼': { definition: 'Gethsemane', partOfSpeech: 'proper noun' },
  '迦百農': { definition: 'Capernaum', partOfSpeech: 'proper noun' },
  '加利利海': { definition: 'Sea of Galilee', partOfSpeech: 'proper noun' },
  '羅馬': { definition: 'Rome', partOfSpeech: 'proper noun' },

  // Common verbs (including TOCFL vocabulary)
  '是': { definition: 'to be', partOfSpeech: 'verb' },
  '有': { definition: 'to have; there is/are', partOfSpeech: 'verb' },
  '說': { definition: 'to say; to speak', partOfSpeech: 'verb' },
  '看': { definition: 'to see; to look', partOfSpeech: 'verb' },
  '來': { definition: 'to come', partOfSpeech: 'verb' },
  '去': { definition: 'to go', partOfSpeech: 'verb' },
  '要': { definition: 'to want; will', partOfSpeech: 'verb' },
  '知道': { definition: 'to know', partOfSpeech: 'verb' },
  '想': { definition: 'to think; to want', partOfSpeech: 'verb' },
  '能': { definition: 'can; to be able to', partOfSpeech: 'verb' },
  '會': { definition: 'can; will; to know how to', partOfSpeech: 'verb' },
  '做': { definition: 'to do; to make', partOfSpeech: 'verb' },
  '給': { definition: 'to give', partOfSpeech: 'verb' },
  '聽': { definition: 'to listen; to hear', partOfSpeech: 'verb' },
  '叫': { definition: 'to call; to be called', partOfSpeech: 'verb' },
  '得': { definition: 'to get; to obtain', partOfSpeech: 'verb' },
  '成': { definition: 'to become; to accomplish', partOfSpeech: 'verb' },
  '行': { definition: 'to walk; to do; okay', partOfSpeech: 'verb' },
  '遵守': { definition: 'to obey; to abide by', partOfSpeech: 'verb' },
  '相信': { definition: 'to believe', partOfSpeech: 'verb' },
  '接受': { definition: 'to accept; to receive', partOfSpeech: 'verb' },
  '吃': { definition: 'to eat', partOfSpeech: 'verb' },
  '喝': { definition: 'to drink', partOfSpeech: 'verb' },
  '讀': { definition: 'to read', partOfSpeech: 'verb' },
  '寫': { definition: 'to write', partOfSpeech: 'verb' },
  '學': { definition: 'to learn; to study', partOfSpeech: 'verb' },
  '教': { definition: 'to teach', partOfSpeech: 'verb' },
  '問': { definition: 'to ask', partOfSpeech: 'verb' },
  '回答': { definition: 'to answer', partOfSpeech: 'verb' },
  '找': { definition: 'to look for; to find', partOfSpeech: 'verb' },
  '用': { definition: 'to use', partOfSpeech: 'verb' },
  '買': { definition: 'to buy', partOfSpeech: 'verb' },
  '賣': { definition: 'to sell', partOfSpeech: 'verb' },
  '坐': { definition: 'to sit', partOfSpeech: 'verb' },
  '站': { definition: 'to stand', partOfSpeech: 'verb' },
  '走': { definition: 'to walk; to leave', partOfSpeech: 'verb' },
  '跑': { definition: 'to run', partOfSpeech: 'verb' },
  '回': { definition: 'to return', partOfSpeech: 'verb' },
  '進': { definition: 'to enter', partOfSpeech: 'verb' },
  '出': { definition: 'to go out; to exit', partOfSpeech: 'verb' },
  '上': { definition: 'to go up; to get on', partOfSpeech: 'verb' },
  '下': { definition: 'to go down; to get off', partOfSpeech: 'verb' },
  '開': { definition: 'to open; to start', partOfSpeech: 'verb' },
  '關': { definition: 'to close; to turn off', partOfSpeech: 'verb' },
  '等': { definition: 'to wait', partOfSpeech: 'verb' },
  '住': { definition: 'to live; to dwell', partOfSpeech: 'verb' },
  '睡': { definition: 'to sleep', partOfSpeech: 'verb' },
  '起': { definition: 'to rise; to get up', partOfSpeech: 'verb' },
  '死': { definition: 'to die', partOfSpeech: 'verb' },
  '活': { definition: 'to live; alive', partOfSpeech: 'verb/adjective' },
  '生': { definition: 'to be born; to give birth', partOfSpeech: 'verb' },
  '帶': { definition: 'to bring; to carry', partOfSpeech: 'verb' },
  '拿': { definition: 'to take; to hold', partOfSpeech: 'verb' },
  '放': { definition: 'to put; to place', partOfSpeech: 'verb' },
  '送': { definition: 'to send; to give as gift', partOfSpeech: 'verb' },
  '穿': { definition: 'to wear; to put on', partOfSpeech: 'verb' },
  '認識': { definition: 'to know; to recognize', partOfSpeech: 'verb' },
  '幫助': { definition: 'to help', partOfSpeech: 'verb' },
  '告訴': { definition: 'to tell', partOfSpeech: 'verb' },
  '遇見': { definition: 'to meet; to encounter', partOfSpeech: 'verb' },
  '跟隨': { definition: 'to follow', partOfSpeech: 'verb' },
  '離開': { definition: 'to leave; to depart', partOfSpeech: 'verb' },
  '經過': { definition: 'to pass through; to experience', partOfSpeech: 'verb' },
  '完成': { definition: 'to complete; to finish', partOfSpeech: 'verb' },
  '開始': { definition: 'to begin; to start', partOfSpeech: 'verb' },
  '結束': { definition: 'to end; to finish', partOfSpeech: 'verb' },
  '希望': { definition: 'to hope; hope', partOfSpeech: 'verb/noun' },
  '需要': { definition: 'to need; need', partOfSpeech: 'verb/noun' },
  '感謝': { definition: 'to thank; gratitude', partOfSpeech: 'verb/noun' },
  '記得': { definition: 'to remember', partOfSpeech: 'verb' },
  '忘記': { definition: 'to forget', partOfSpeech: 'verb' },
  '明白': { definition: 'to understand', partOfSpeech: 'verb' },
  '懂': { definition: 'to understand', partOfSpeech: 'verb' },
  '改變': { definition: 'to change', partOfSpeech: 'verb' },
  '願意': { definition: 'to be willing', partOfSpeech: 'verb' },
  '應該': { definition: 'should; ought to', partOfSpeech: 'verb' },
  '必須': { definition: 'must; have to', partOfSpeech: 'verb' },
  '可以': { definition: 'can; may', partOfSpeech: 'verb' },

  // Common nouns (including TOCFL vocabulary)
  '人': { definition: 'person; people', partOfSpeech: 'noun' },
  '時候': { definition: 'time; moment', partOfSpeech: 'noun' },
  '地方': { definition: 'place', partOfSpeech: 'noun' },
  '東西': { definition: 'thing; object', partOfSpeech: 'noun' },
  '生命': { definition: 'life', partOfSpeech: 'noun' },
  '世界': { definition: 'world', partOfSpeech: 'noun' },
  '天': { definition: 'sky; heaven; day', partOfSpeech: 'noun' },
  '地': { definition: 'earth; ground', partOfSpeech: 'noun' },
  '心': { definition: 'heart; mind', partOfSpeech: 'noun' },
  '眼': { definition: 'eye', partOfSpeech: 'noun' },
  '手': { definition: 'hand', partOfSpeech: 'noun' },
  '口': { definition: 'mouth', partOfSpeech: 'noun' },
  '話': { definition: 'words; speech', partOfSpeech: 'noun' },
  '道': { definition: 'way; path; word (logos)', partOfSpeech: 'noun' },
  '事': { definition: 'matter; thing; affair', partOfSpeech: 'noun' },
  '日子': { definition: 'day; date', partOfSpeech: 'noun' },
  '年': { definition: 'year', partOfSpeech: 'noun' },
  '名': { definition: 'name', partOfSpeech: 'noun' },
  '父': { definition: 'father', partOfSpeech: 'noun' },
  '母': { definition: 'mother', partOfSpeech: 'noun' },
  '子': { definition: 'son; child', partOfSpeech: 'noun' },
  '兒子': { definition: 'son', partOfSpeech: 'noun' },
  '女兒': { definition: 'daughter', partOfSpeech: 'noun' },
  '弟兄': { definition: 'brother(s); brethren', partOfSpeech: 'noun' },
  '家': { definition: 'home; family', partOfSpeech: 'noun' },
  '家庭': { definition: 'family', partOfSpeech: 'noun' },
  '朋友': { definition: 'friend', partOfSpeech: 'noun' },
  '老師': { definition: 'teacher', partOfSpeech: 'noun' },
  '學生': { definition: 'student', partOfSpeech: 'noun' },
  '工作': { definition: 'work; job', partOfSpeech: 'noun' },
  '書': { definition: 'book', partOfSpeech: 'noun' },
  '水': { definition: 'water', partOfSpeech: 'noun' },
  '飯': { definition: 'rice; meal', partOfSpeech: 'noun' },
  '麵包': { definition: 'bread', partOfSpeech: 'noun' },
  '酒': { definition: 'wine; alcohol', partOfSpeech: 'noun' },
  '魚': { definition: 'fish', partOfSpeech: 'noun' },
  '肉': { definition: 'meat', partOfSpeech: 'noun' },
  '門': { definition: 'door; gate', partOfSpeech: 'noun' },
  '路': { definition: 'road; way', partOfSpeech: 'noun' },
  '山': { definition: 'mountain', partOfSpeech: 'noun' },
  '海': { definition: 'sea', partOfSpeech: 'noun' },
  '河': { definition: 'river', partOfSpeech: 'noun' },
  '樹': { definition: 'tree', partOfSpeech: 'noun' },
  '光': { definition: 'light', partOfSpeech: 'noun' },
  '火': { definition: 'fire', partOfSpeech: 'noun' },
  '風': { definition: 'wind', partOfSpeech: 'noun' },
  '雨': { definition: 'rain', partOfSpeech: 'noun' },
  '雲': { definition: 'cloud', partOfSpeech: 'noun' },
  '石頭': { definition: 'stone; rock', partOfSpeech: 'noun' },
  '身體': { definition: 'body', partOfSpeech: 'noun' },
  '頭': { definition: 'head', partOfSpeech: 'noun' },
  '耳朵': { definition: 'ear', partOfSpeech: 'noun' },
  '腳': { definition: 'foot; leg', partOfSpeech: 'noun' },
  '血': { definition: 'blood', partOfSpeech: 'noun' },
  '聲音': { definition: 'sound; voice', partOfSpeech: 'noun' },
  '力量': { definition: 'strength; power', partOfSpeech: 'noun' },
  '能力': { definition: 'ability; capability', partOfSpeech: 'noun' },
  '智慧': { definition: 'wisdom', partOfSpeech: 'noun' },
  '真理': { definition: 'truth', partOfSpeech: 'noun' },
  '平安': { definition: 'peace', partOfSpeech: 'noun' },
  '喜樂': { definition: 'joy', partOfSpeech: 'noun' },
  '痛苦': { definition: 'suffering; pain', partOfSpeech: 'noun' },
  '苦難': { definition: 'hardship; tribulation', partOfSpeech: 'noun' },
  '困難': { definition: 'difficulty', partOfSpeech: 'noun' },
  '問題': { definition: 'question; problem', partOfSpeech: 'noun' },
  '辦法': { definition: 'method; way', partOfSpeech: 'noun' },
  '意思': { definition: 'meaning; intention', partOfSpeech: 'noun' },
  '時間': { definition: 'time', partOfSpeech: 'noun' },
  '今天': { definition: 'today', partOfSpeech: 'noun' },
  '明天': { definition: 'tomorrow', partOfSpeech: 'noun' },
  '昨天': { definition: 'yesterday', partOfSpeech: 'noun' },
  '早上': { definition: 'morning', partOfSpeech: 'noun' },
  '晚上': { definition: 'evening; night', partOfSpeech: 'noun' },
  '夜': { definition: 'night', partOfSpeech: 'noun' },
  '月': { definition: 'month; moon', partOfSpeech: 'noun' },
  '星': { definition: 'star', partOfSpeech: 'noun' },
  '國': { definition: 'country; nation', partOfSpeech: 'noun' },
  '城': { definition: 'city; town', partOfSpeech: 'noun' },
  '村': { definition: 'village', partOfSpeech: 'noun' },
  '房子': { definition: 'house', partOfSpeech: 'noun' },
  '衣服': { definition: 'clothes', partOfSpeech: 'noun' },
  '錢': { definition: 'money', partOfSpeech: 'noun' },
  '金': { definition: 'gold', partOfSpeech: 'noun' },
  '銀': { definition: 'silver', partOfSpeech: 'noun' },
  '寶': { definition: 'treasure; precious', partOfSpeech: 'noun/adjective' },
  '王': { definition: 'king', partOfSpeech: 'noun' },
  '主': { definition: 'lord; master', partOfSpeech: 'noun' },
  '僕人': { definition: 'servant', partOfSpeech: 'noun' },
  '百姓': { definition: 'people; common people', partOfSpeech: 'noun' },
  '民': { definition: 'people; folk', partOfSpeech: 'noun' },
  '鄰舍': { definition: 'neighbor', partOfSpeech: 'noun' },
  '仇敵': { definition: 'enemy', partOfSpeech: 'noun' },

  // Pronouns
  '我': { definition: 'I; me', partOfSpeech: 'pronoun' },
  '你': { definition: 'you (singular)', partOfSpeech: 'pronoun' },
  '他': { definition: 'he; him', partOfSpeech: 'pronoun' },
  '她': { definition: 'she; her', partOfSpeech: 'pronoun' },
  '它': { definition: 'it', partOfSpeech: 'pronoun' },
  '我們': { definition: 'we; us', partOfSpeech: 'pronoun' },
  '你們': { definition: 'you (plural)', partOfSpeech: 'pronoun' },
  '他們': { definition: 'they; them (male/mixed)', partOfSpeech: 'pronoun' },
  '她們': { definition: 'they; them (female)', partOfSpeech: 'pronoun' },
  '這': { definition: 'this', partOfSpeech: 'pronoun' },
  '那': { definition: 'that', partOfSpeech: 'pronoun' },
  '誰': { definition: 'who', partOfSpeech: 'pronoun' },
  '什麼': { definition: 'what', partOfSpeech: 'pronoun' },

  // Adjectives (including TOCFL vocabulary)
  '好': { definition: 'good', partOfSpeech: 'adjective' },
  '大': { definition: 'big; great', partOfSpeech: 'adjective' },
  '小': { definition: 'small; little', partOfSpeech: 'adjective' },
  '多': { definition: 'many; much; more', partOfSpeech: 'adjective' },
  '少': { definition: 'few; little; less', partOfSpeech: 'adjective' },
  '真': { definition: 'true; real', partOfSpeech: 'adjective' },
  '新': { definition: 'new', partOfSpeech: 'adjective' },
  '舊': { definition: 'old', partOfSpeech: 'adjective' },
  '高': { definition: 'high; tall', partOfSpeech: 'adjective' },
  '低': { definition: 'low', partOfSpeech: 'adjective' },
  '長': { definition: 'long', partOfSpeech: 'adjective' },
  '短': { definition: 'short', partOfSpeech: 'adjective' },
  '遠': { definition: 'far; distant', partOfSpeech: 'adjective' },
  '近': { definition: 'near; close', partOfSpeech: 'adjective' },
  '快': { definition: 'fast; quick', partOfSpeech: 'adjective' },
  '慢': { definition: 'slow', partOfSpeech: 'adjective' },
  '早': { definition: 'early', partOfSpeech: 'adjective' },
  '晚': { definition: 'late', partOfSpeech: 'adjective' },
  '深': { definition: 'deep', partOfSpeech: 'adjective' },
  '淺': { definition: 'shallow', partOfSpeech: 'adjective' },
  '重': { definition: 'heavy; important', partOfSpeech: 'adjective' },
  '輕': { definition: 'light (weight)', partOfSpeech: 'adjective' },
  '強': { definition: 'strong', partOfSpeech: 'adjective' },
  '弱': { definition: 'weak', partOfSpeech: 'adjective' },
  '冷': { definition: 'cold', partOfSpeech: 'adjective' },
  '熱': { definition: 'hot', partOfSpeech: 'adjective' },
  '暖': { definition: 'warm', partOfSpeech: 'adjective' },
  '乾': { definition: 'dry', partOfSpeech: 'adjective' },
  '濕': { definition: 'wet', partOfSpeech: 'adjective' },
  '明': { definition: 'bright; clear', partOfSpeech: 'adjective' },
  '暗': { definition: 'dark', partOfSpeech: 'adjective' },
  '美': { definition: 'beautiful', partOfSpeech: 'adjective' },
  '醜': { definition: 'ugly', partOfSpeech: 'adjective' },
  '乾淨': { definition: 'clean', partOfSpeech: 'adjective' },
  '髒': { definition: 'dirty', partOfSpeech: 'adjective' },
  '難': { definition: 'difficult', partOfSpeech: 'adjective' },
  '容易': { definition: 'easy', partOfSpeech: 'adjective' },
  '簡單': { definition: 'simple', partOfSpeech: 'adjective' },
  '複雜': { definition: 'complex; complicated', partOfSpeech: 'adjective' },
  '清楚': { definition: 'clear', partOfSpeech: 'adjective' },
  '滿': { definition: 'full', partOfSpeech: 'adjective' },
  '空': { definition: 'empty', partOfSpeech: 'adjective' },
  '完全': { definition: 'complete; perfect', partOfSpeech: 'adjective' },
  '完整': { definition: 'complete; intact', partOfSpeech: 'adjective' },
  '正確': { definition: 'correct', partOfSpeech: 'adjective' },
  '錯': { definition: 'wrong; mistaken', partOfSpeech: 'adjective' },
  '對': { definition: 'right; correct', partOfSpeech: 'adjective' },
  '安靜': { definition: 'quiet; peaceful', partOfSpeech: 'adjective' },
  '吵': { definition: 'noisy', partOfSpeech: 'adjective' },
  '自由': { definition: 'free; freedom', partOfSpeech: 'adjective/noun' },
  '危險': { definition: 'dangerous; danger', partOfSpeech: 'adjective/noun' },
  '安全': { definition: 'safe; safety', partOfSpeech: 'adjective/noun' },
  '富': { definition: 'rich; wealthy', partOfSpeech: 'adjective' },
  '窮': { definition: 'poor', partOfSpeech: 'adjective' },
  '貴': { definition: 'expensive; noble', partOfSpeech: 'adjective' },
  '賤': { definition: 'cheap; lowly', partOfSpeech: 'adjective' },
  '喜歡': { definition: 'to like; favorite', partOfSpeech: 'verb/adjective' },
  '高興': { definition: 'happy; glad', partOfSpeech: 'adjective' },
  '快樂': { definition: 'happy; joyful', partOfSpeech: 'adjective' },
  '悲傷': { definition: 'sad; sorrowful', partOfSpeech: 'adjective' },
  '害怕': { definition: 'afraid; scared', partOfSpeech: 'adjective/verb' },
  '生氣': { definition: 'angry', partOfSpeech: 'adjective' },
  '驕傲': { definition: 'proud; arrogant', partOfSpeech: 'adjective' },
  '謙卑': { definition: 'humble', partOfSpeech: 'adjective' },
  '勇敢': { definition: 'brave; courageous', partOfSpeech: 'adjective' },
  '誠實': { definition: 'honest', partOfSpeech: 'adjective' },
  '忠心': { definition: 'loyal; faithful', partOfSpeech: 'adjective' },
  '善良': { definition: 'kind; good-hearted', partOfSpeech: 'adjective' },
  '邪惡': { definition: 'evil; wicked', partOfSpeech: 'adjective' },
  '沒有': { definition: 'to not have; there is not', partOfSpeech: 'verb' },
  '全': { definition: 'whole; entire; all', partOfSpeech: 'adjective' },
  '永遠': { definition: 'forever; eternal', partOfSpeech: 'adverb/adjective' },
  '重要': { definition: 'important', partOfSpeech: 'adjective' },
  '必要': { definition: 'necessary', partOfSpeech: 'adjective' },

  // Common adverbs and particles (including TOCFL vocabulary)
  '不': { definition: 'not; no', partOfSpeech: 'adverb' },
  '沒': { definition: 'not; did not', partOfSpeech: 'adverb' },
  '也': { definition: 'also; too', partOfSpeech: 'adverb' },
  '都': { definition: 'all; both', partOfSpeech: 'adverb' },
  '很': { definition: 'very', partOfSpeech: 'adverb' },
  '就': { definition: 'then; right away', partOfSpeech: 'adverb' },
  '又': { definition: 'again; also', partOfSpeech: 'adverb' },
  '還': { definition: 'still; yet; also', partOfSpeech: 'adverb' },
  '才': { definition: 'only then; just', partOfSpeech: 'adverb' },
  '只': { definition: 'only; just', partOfSpeech: 'adverb' },
  '再': { definition: 'again; once more', partOfSpeech: 'adverb' },
  '正': { definition: 'just; right now', partOfSpeech: 'adverb' },
  '正在': { definition: 'in the process of', partOfSpeech: 'adverb' },
  '一起': { definition: 'together', partOfSpeech: 'adverb' },
  '一定': { definition: 'definitely; certainly', partOfSpeech: 'adverb' },
  '已經': { definition: 'already', partOfSpeech: 'adverb' },
  '常常': { definition: 'often', partOfSpeech: 'adverb' },
  '從來': { definition: 'always; ever (in negatives)', partOfSpeech: 'adverb' },
  '立刻': { definition: 'immediately', partOfSpeech: 'adverb' },
  '馬上': { definition: 'immediately; at once', partOfSpeech: 'adverb' },
  '然後': { definition: 'then; after that', partOfSpeech: 'adverb' },
  '首先': { definition: 'first; firstly', partOfSpeech: 'adverb' },
  '最後': { definition: 'finally; last', partOfSpeech: 'adverb' },
  '其實': { definition: 'actually; in fact', partOfSpeech: 'adverb' },
  '真正': { definition: 'really; truly', partOfSpeech: 'adverb/adjective' },
  '實在': { definition: 'really; indeed', partOfSpeech: 'adverb' },
  '更': { definition: 'more; even more', partOfSpeech: 'adverb' },
  '最': { definition: 'most', partOfSpeech: 'adverb' },
  '太': { definition: 'too; excessively', partOfSpeech: 'adverb' },
  '非常': { definition: 'very; extremely', partOfSpeech: 'adverb' },
  '特別': { definition: 'especially; particularly', partOfSpeech: 'adverb' },
  '如何': { definition: 'how', partOfSpeech: 'adverb' },
  '怎麼': { definition: 'how; why', partOfSpeech: 'adverb' },
  '為何': { definition: 'why; for what reason', partOfSpeech: 'adverb' },
  '為什麼': { definition: 'why', partOfSpeech: 'adverb' },
  '的': { definition: 'possessive particle', partOfSpeech: 'particle' },
  '了': { definition: 'completion particle', partOfSpeech: 'particle' },
  '著': { definition: 'continuous aspect particle', partOfSpeech: 'particle' },
  '過': { definition: 'experiential aspect particle', partOfSpeech: 'particle' },
  '嗎': { definition: 'question particle', partOfSpeech: 'particle' },
  '呢': { definition: 'question particle', partOfSpeech: 'particle' },
  '吧': { definition: 'suggestion particle', partOfSpeech: 'particle' },
  '啊': { definition: 'exclamatory particle', partOfSpeech: 'particle' },
  '在': { definition: 'at; in; on', partOfSpeech: 'preposition' },
  '從': { definition: 'from', partOfSpeech: 'preposition' },
  '到': { definition: 'to; until', partOfSpeech: 'preposition' },
  '向': { definition: 'towards; to', partOfSpeech: 'preposition' },
  '為': { definition: 'for; because of', partOfSpeech: 'preposition' },
  '與': { definition: 'and; with', partOfSpeech: 'preposition' },
  '跟': { definition: 'with; and', partOfSpeech: 'preposition' },
  '同': { definition: 'with; same', partOfSpeech: 'preposition' },
  '因': { definition: 'because of', partOfSpeech: 'preposition' },
  '因為': { definition: 'because', partOfSpeech: 'conjunction' },
  '所以': { definition: 'therefore; so', partOfSpeech: 'conjunction' },
  '但是': { definition: 'but; however', partOfSpeech: 'conjunction' },
  '可是': { definition: 'but; however', partOfSpeech: 'conjunction' },
  '不過': { definition: 'but; however', partOfSpeech: 'conjunction' },
  '雖然': { definition: 'although', partOfSpeech: 'conjunction' },
  '如果': { definition: 'if', partOfSpeech: 'conjunction' },
  '若': { definition: 'if', partOfSpeech: 'conjunction' },
  '或': { definition: 'or', partOfSpeech: 'conjunction' },
  '或者': { definition: 'or; either...or', partOfSpeech: 'conjunction' },
  '而': { definition: 'and; yet', partOfSpeech: 'conjunction' },
  '並': { definition: 'and; moreover', partOfSpeech: 'conjunction' },

  // Numbers and measure words (including TOCFL vocabulary)
  '一': { definition: 'one', partOfSpeech: 'number' },
  '二': { definition: 'two', partOfSpeech: 'number' },
  '三': { definition: 'three', partOfSpeech: 'number' },
  '四': { definition: 'four', partOfSpeech: 'number' },
  '五': { definition: 'five', partOfSpeech: 'number' },
  '六': { definition: 'six', partOfSpeech: 'number' },
  '七': { definition: 'seven', partOfSpeech: 'number' },
  '八': { definition: 'eight', partOfSpeech: 'number' },
  '九': { definition: 'nine', partOfSpeech: 'number' },
  '十': { definition: 'ten', partOfSpeech: 'number' },
  '百': { definition: 'hundred', partOfSpeech: 'number' },
  '千': { definition: 'thousand', partOfSpeech: 'number' },
  '萬': { definition: 'ten thousand', partOfSpeech: 'number' },
  '億': { definition: 'hundred million', partOfSpeech: 'number' },
  '零': { definition: 'zero', partOfSpeech: 'number' },
  '兩': { definition: 'two (for measure words)', partOfSpeech: 'number' },
  '半': { definition: 'half', partOfSpeech: 'number' },
  '第': { definition: 'ordinal prefix (first, second...)', partOfSpeech: 'prefix' },
  '個': { definition: 'general measure word', partOfSpeech: 'measure word' },
  '位': { definition: 'measure word (polite, for people)', partOfSpeech: 'measure word' },
  '些': { definition: 'some; a few', partOfSpeech: 'measure word' },
  '次': { definition: 'measure word for times/occurrences', partOfSpeech: 'measure word' },
  '遍': { definition: 'measure word for complete actions', partOfSpeech: 'measure word' },
  '本': { definition: 'measure word for books', partOfSpeech: 'measure word' },
  '張': { definition: 'measure word for flat objects', partOfSpeech: 'measure word' },
  '條': { definition: 'measure word for long objects', partOfSpeech: 'measure word' },
  '件': { definition: 'measure word for matters/clothing', partOfSpeech: 'measure word' },
  '隻': { definition: 'measure word for animals', partOfSpeech: 'measure word' },
  '棵': { definition: 'measure word for trees', partOfSpeech: 'measure word' },
  '座': { definition: 'measure word for buildings/mountains', partOfSpeech: 'measure word' },
  '雙': { definition: 'measure word for pairs', partOfSpeech: 'measure word' },
  '群': { definition: 'measure word for groups', partOfSpeech: 'measure word' },
  '片': { definition: 'measure word for slices/expanses', partOfSpeech: 'measure word' },
  '杯': { definition: 'measure word for cups', partOfSpeech: 'measure word' },
  '碗': { definition: 'measure word for bowls', partOfSpeech: 'measure word' },

  // HSK 1-3 Vocabulary (additional words for biblical contexts)
  '愛好': { definition: 'to like; to be fond of; to take pleasure in; to be keen on; interest; hobby', partOfSpeech: 'noun/verb' },
  '爸': { definition: 'father; dad; pa', partOfSpeech: 'noun' },
  '爸爸': { definition: '(coll.) father; dad', partOfSpeech: 'noun' },
  '白': { definition: 'surname Bai', partOfSpeech: 'adjective' },
  '白天': { definition: 'daytime; during the day; day', partOfSpeech: 'time word' },
  '班': { definition: 'surname Ban', partOfSpeech: 'noun' },
  '半年': { definition: 'half a year', partOfSpeech: 'person name' },
  '半天': { definition: 'half of the day; a long time; quite a while', partOfSpeech: 'mq/time word' },
  '幇': { definition: 'old variant of 帮', partOfSpeech: 'verb/measure word' },
  '幫忙': { definition: 'to help; to lend a hand; to do a favor', partOfSpeech: 'verb/noun/verb' },
  '包子': { definition: 'bao (steamed stuffed bun)', partOfSpeech: 'noun' },
  '杯子': { definition: 'cup; glass', partOfSpeech: 'noun' },
  '北邊': { definition: 'north; north side; northern part', partOfSpeech: 'word' },
  '北京': { definition: 'Beijing, capital of the People\'s Republic of China', partOfSpeech: 'place name' },
  '本子': { definition: 'book; notebook; Japanese-style self-published comic (esp. an erotic one), aka "dōjinshi"', partOfSpeech: 'noun' },
  '別的': { definition: 'else; other', partOfSpeech: 'pronoun' },
  '別人': { definition: 'other people; others; other person', partOfSpeech: 'pronoun' },
  '病人': { definition: 'sick person; patient; invalid', partOfSpeech: 'noun' },
  '不大': { definition: 'not very; not too; not often', partOfSpeech: 'word' },
  '不對': { definition: 'incorrect; wrong; amiss', partOfSpeech: 'adjective' },
  '不用': { definition: 'need not', partOfSpeech: 'word' },
  '唱歌': { definition: 'to sing a song', partOfSpeech: 'verb/noun/verb' },
  '車票': { definition: 'ticket (for a bus or train)', partOfSpeech: 'noun' },
  '車上': { definition: 'Car', partOfSpeech: 'word' },
  '車站': { definition: 'rail station; bus stop', partOfSpeech: 'noun' },
  '吃飯': { definition: 'to have a meal; to eat; to make a living', partOfSpeech: 'verb/noun/verb' },
  '出來': { definition: 'to come out; to appear; to arise', partOfSpeech: 'verb' },
  '出去': { definition: 'to go out', partOfSpeech: 'verb' },
  '打車': { definition: 'to take a taxi (in town); to hitch a lift', partOfSpeech: 'verb' },
  '打開': { definition: 'to open; to show (a ticket); to turn on', partOfSpeech: 'verb' },
  '打球': { definition: 'to play ball; to play with a ball', partOfSpeech: 'verb/noun/verb' },
  '大學': { definition: 'the Great Learning, one of the Four Books 四书 in Confucianism', partOfSpeech: 'noun' },
  '地點': { definition: 'place; site; location', partOfSpeech: 'noun' },
  '地上': { definition: 'on the ground; on the floor', partOfSpeech: 'word' },
  '地圖': { definition: 'map', partOfSpeech: 'noun' },
  '得到': { definition: 'to get; to obtain; to receive', partOfSpeech: 'verb' },
  '弟弟': { definition: 'younger brother', partOfSpeech: 'noun' },
  '第二': { definition: 'second; number two; next', partOfSpeech: 'measure word' },
  '電話': { definition: 'telephone; phone call; phone number', partOfSpeech: 'noun' },
  '電腦': { definition: 'computer', partOfSpeech: 'noun' },
  '電視': { definition: 'television; TV', partOfSpeech: 'noun' },
  '電影': { definition: 'movie; film', partOfSpeech: 'noun' },
  '東邊': { definition: 'east; east side; eastern part', partOfSpeech: 'word' },
  '動作': { definition: 'movement; motion; action; to act; to move', partOfSpeech: 'noun/verb' },
  '讀書': { definition: 'to read a book; to study; to attend school', partOfSpeech: 'verb/noun/verb' },
  '多少': { definition: 'number; amount; somewhat', partOfSpeech: 'pronoun' },
  '飯店': { definition: 'restaurant; hotel', partOfSpeech: 'noun' },
  '房間': { definition: 'room', partOfSpeech: 'noun' },
  '放假': { definition: 'to have a holiday or vacation', partOfSpeech: 'verb' },
  '放學': { definition: 'to dismiss students at the end of the school day', partOfSpeech: 'verb' },
  '飛機': { definition: 'airplane', partOfSpeech: 'noun' },
  '哥哥': { definition: 'older brother', partOfSpeech: 'noun' },
  '工人': { definition: 'worker', partOfSpeech: 'noun' },
  '關上': { definition: 'to close (a door); to turn off (light, electrical equipment etc)', partOfSpeech: 'verb' },
  '國家': { definition: 'country; nation; state', partOfSpeech: 'noun' },
  '國外': { definition: 'abroad; external (affairs); overseas', partOfSpeech: 'word' },
  '還是': { definition: 'still (as before); had better; unexpectedly', partOfSpeech: 'conjunction' },
  '還有': { definition: 'furthermore; in addition; still', partOfSpeech: 'verb' },
  '孩子': { definition: 'child', partOfSpeech: 'noun' },
  '漢語': { definition: 'Chinese language', partOfSpeech: 'proper noun' },
  '漢字': { definition: 'Chinese character; Japanese: kanji; Korean: hanja', partOfSpeech: 'proper noun/noun' },
  '好吃': { definition: 'tasty; delicious', partOfSpeech: 'adjective' },
  '好看': { definition: 'good-looking; nice-looking; good (of a movie, book, TV show etc)', partOfSpeech: 'adjective' },
  '好聽': { definition: 'pleasant to hear', partOfSpeech: 'adjective' },
  '後邊': { definition: 'the back; the rear; the last bit; behind; near the end; at the back; later; afterwards', partOfSpeech: 'word' },
  '後天': { definition: 'the day after tomorrow; life after birth (the period in which one develops through experiences, contrasted with 天); acquired (not innate or congenital)', partOfSpeech: 'noun/time word' },
  '回到': { definition: 'to return to', partOfSpeech: 'verb' },
  '回家': { definition: 'to return home', partOfSpeech: 'verb' },
  '回來': { definition: 'to return; to come back', partOfSpeech: 'verb' },
  '回去': { definition: 'to return; to go back', partOfSpeech: 'verb' },
  '火車': { definition: 'train', partOfSpeech: 'noun' },
  '機場': { definition: 'airport; airfield; (slang) service provider for Shadowsocks or similar software for circumventing Internet censorship', partOfSpeech: 'noun' },
  '機票': { definition: 'air ticket; passenger ticket', partOfSpeech: 'noun' },
  '雞蛋': { definition: '(chicken) egg; hen\'s egg', partOfSpeech: 'noun' },
  '記住': { definition: 'to remember; to bear in mind; to learn by heart', partOfSpeech: 'verb' },
  '家裡': { definition: 'home', partOfSpeech: 's/noun' },
  '家人': { definition: 'family member; (old) servant', partOfSpeech: 'noun/person name' },
  '見面': { definition: 'to meet; to see each other', partOfSpeech: 'verb' },
  '介紹': { definition: 'to introduce (sb to sb); to give a presentation; to present (sb for a job etc)', partOfSpeech: 'verb/noun/verb' },
  '姐姐': { definition: 'older sister', partOfSpeech: 'noun' },
  '今年': { definition: 'this year', partOfSpeech: 'time word' },
  '進來': { definition: 'to come in', partOfSpeech: 'verb' },
  '進去': { definition: 'to go in', partOfSpeech: 'verb' },
  '覺得': { definition: 'to think that ...; to feel that ...; to feel (uncomfortable etc)', partOfSpeech: 'verb' },
  '開車': { definition: 'to drive a car', partOfSpeech: 'verb/noun/verb' },
  '開會': { definition: 'to hold a meeting; to attend a meeting', partOfSpeech: 'verb' },
  '看病': { definition: 'to visit a doctor; to see a patient', partOfSpeech: 'verb/noun/verb' },
  '看到': { definition: 'to see', partOfSpeech: 'verb' },
  '看見': { definition: 'to see; to catch sight of', partOfSpeech: 'verb' },
  '考試': { definition: 'to take an exam; exam', partOfSpeech: 'noun/verb/verb' },
  '課本': { definition: 'textbook', partOfSpeech: 'noun' },
  '課文': { definition: 'text', partOfSpeech: 'noun' },
  '來到': { definition: 'to arrive; to come', partOfSpeech: 'verb' },
  '老人': { definition: 'old man or woman; the elderly; one\'s aged parents or grandparents', partOfSpeech: 'noun' },
  '裡邊': { definition: 'inside', partOfSpeech: 'word' },
  '樓上': { definition: 'upstairs; (Internet slang) previous poster in a forum thread', partOfSpeech: 's/f' },
  '樓下': { definition: 'downstairs', partOfSpeech: 'word' },
  '路口': { definition: 'crossing; intersection (of roads)', partOfSpeech: 'noun' },
  '路上': { definition: 'on the road; on a journey; road surface', partOfSpeech: 'word' },
  '媽媽': { definition: 'mama; mommy; mother', partOfSpeech: 'noun' },
  '馬路': { definition: 'street; road', partOfSpeech: 'noun' },
  '妹妹': { definition: 'younger sister; young woman', partOfSpeech: 'noun' },
  '門口': { definition: 'doorway; gate', partOfSpeech: 'word' },
  '門票': { definition: 'ticket (for theater, cinema etc)', partOfSpeech: 'noun' },
  '米飯': { definition: '(cooked) rice', partOfSpeech: 'noun' },
  '名字': { definition: 'name (of a person or thing)', partOfSpeech: 'noun' },
  '明年': { definition: 'next year', partOfSpeech: 'time word' },
  '哪兒': { definition: 'where?; wherever; anywhere; somewhere; (used in rhetorical questions) how can ...?; how could ...?', partOfSpeech: 'pronoun' },
  '哪裏': { definition: 'where?; somewhere; anywhere', partOfSpeech: 'pronoun' },
  '哪些': { definition: 'which ones?; who?; what?', partOfSpeech: 'pronoun' },
  '那邊': { definition: 'over there; yonder', partOfSpeech: 'pronoun' },
  '那兒': { definition: 'there', partOfSpeech: 'pronoun' },
  '那裏': { definition: 'there; that place', partOfSpeech: 'pronoun' },
  '那些': { definition: 'those', partOfSpeech: 'pronoun' },
  '奶奶': { definition: '(informal) grandma (paternal grandmother); (respectful) mistress of the house; (coll.) boobies', partOfSpeech: 'noun' },
  '男人': { definition: 'a man; a male; men', partOfSpeech: 'noun' },
  '男生': { definition: 'schoolboy; male student; boy', partOfSpeech: 'noun' },
  '南邊': { definition: 'south; south side; southern part', partOfSpeech: 'word' },
  '牛奶': { definition: 'cow\'s milk', partOfSpeech: 'noun' },
  '女人': { definition: 'woman', partOfSpeech: 'noun' },
  '女生': { definition: 'schoolgirl; female student; girl', partOfSpeech: 'noun/person name' },
  '旁邊': { definition: 'side; adjacent place', partOfSpeech: 'word' },
  '起床': { definition: 'to get out of bed; to get up', partOfSpeech: 'verb' },
  '起來': { definition: 'to stand up; to get up; also pr. [qǐ lái]', partOfSpeech: 'verb' },
  '汽車': { definition: 'car; automobile; bus', partOfSpeech: 'noun' },
  '前邊': { definition: 'front; the front side; in front of', partOfSpeech: 'word' },
  '前天': { definition: 'the day before yesterday', partOfSpeech: 'time word/noun' },
  '錢包': { definition: 'purse; wallet', partOfSpeech: 'noun' },
  '請假': { definition: 'to request leave of absence', partOfSpeech: 'verb' },
  '請進': { definition: '"please come in"', partOfSpeech: 'noun' },
  '請問': { definition: 'Excuse me, may I ask...?', partOfSpeech: 'verb' },
  '請坐': { definition: 'please, have a seat', partOfSpeech: 'noun' },
  '去年': { definition: 'last year', partOfSpeech: 'time word' },
  '認真': { definition: 'conscientious; earnest; serious', partOfSpeech: 'adjective/adverb' },
  '日期': { definition: 'date', partOfSpeech: 'noun' },
  '商場': { definition: 'shopping mall; shopping center; department store', partOfSpeech: 'noun' },
  '商店': { definition: 'store; shop', partOfSpeech: 'noun' },
  '上班': { definition: 'to go to work; to be on duty; to start work', partOfSpeech: 'verb/noun/verb' },
  '上邊': { definition: 'the top; above; overhead', partOfSpeech: 'f/noun' },
  '上車': { definition: 'to get on or into (a bus, train, car etc)', partOfSpeech: 'verb' },
  '上次': { definition: 'last time', partOfSpeech: 'time word' },
  '上課': { definition: 'to go to class; to attend class; to go to teach a class', partOfSpeech: 'verb/noun/verb' },
  '上網': { definition: 'to go online; to connect to the Internet; (of a document etc) to be uploaded to the Internet', partOfSpeech: 'verb/noun/verb' },
  '上午': { definition: 'morning', partOfSpeech: 'time word' },
  '上學': { definition: 'to go to school; to attend school', partOfSpeech: 'verb' },
  '身上': { definition: 'on the body; at hand; among', partOfSpeech: 'word' },
  '生病': { definition: 'to fall ill', partOfSpeech: 'verb' },
  '生日': { definition: 'birthday', partOfSpeech: 'noun' },
  '手機': { definition: 'cell phone; mobile phone', partOfSpeech: 'noun' },
  '書包': { definition: 'schoolbag; satchel; bookbag', partOfSpeech: 'noun' },
  '書店': { definition: 'bookstore', partOfSpeech: 'noun' },
  '水果': { definition: 'fruit', partOfSpeech: 'noun' },
  '睡覺': { definition: 'to go to bed; to sleep', partOfSpeech: 'verb' },
  '說話': { definition: 'to speak; to say; to talk', partOfSpeech: 'verb/noun/verb' },
  '天氣': { definition: 'weather', partOfSpeech: 'noun' },
  '聽到': { definition: 'to hear', partOfSpeech: 'verb' },
  '聽見': { definition: 'to hear', partOfSpeech: 'verb' },
  '聽寫': { definition: '(of a pupil) to write down (in a dictation exercise); dictation; (music) to transcribe by ear', partOfSpeech: 'verb/noun/verb' },
  '同學': { definition: 'to study at the same school; fellow student; classmate', partOfSpeech: 'noun' },
  '外邊': { definition: 'outside; outer surface; abroad', partOfSpeech: 'word' },
  '外國': { definition: 'foreign (country)', partOfSpeech: 'noun' },
  '外語': { definition: 'foreign language', partOfSpeech: 'noun' },
  '玩兒': { definition: 'to play; to have fun; to hang out', partOfSpeech: 'verb' },
  '晚飯': { definition: 'evening meal; dinner; supper', partOfSpeech: 'noun' },
  '網上': { definition: 'online', partOfSpeech: 'word' },
  '網友': { definition: 'online friend; Internet user', partOfSpeech: 'noun' },
  '午飯': { definition: 'lunch', partOfSpeech: 'noun' },
  '西邊': { definition: 'west; west side; western part', partOfSpeech: 'f/person name' },
  '下班': { definition: 'to finish work; to get off work', partOfSpeech: 'verb/noun/verb' },
  '下邊': { definition: 'under; the underside; below', partOfSpeech: 'word' },
  '下車': { definition: 'to get off or out of (a bus, train, car etc)', partOfSpeech: 'verb/noun/verb' },
  '下次': { definition: 'next time', partOfSpeech: 'time word' },
  '下課': { definition: 'to finish class; to get out of class; (fig.) (esp. of a sports coach) to be dismissed', partOfSpeech: 'verb/noun/verb' },
  '下午': { definition: 'afternoon; p.m.', partOfSpeech: 'time word' },
  '下雨': { definition: 'to rain', partOfSpeech: 'verb' },
  '先生': { definition: 'teacher; gentleman; sir; mister (Mr.); husband', partOfSpeech: 'noun' },
  '現在': { definition: 'now; at present; at the moment', partOfSpeech: 'time word' },
  '小姐': { definition: 'young lady; miss; (slang) prostitute', partOfSpeech: 'noun' },
  '小時': { definition: 'hour', partOfSpeech: 'noun/measure word' },
  '小學': { definition: 'elementary school; primary school', partOfSpeech: 'noun' },
  '謝謝': { definition: 'to thank; thanks; thank you', partOfSpeech: 'verb' },
  '新年': { definition: 'New Year', partOfSpeech: 'time word' },
  '星期': { definition: 'week; day of the week; Sunday', partOfSpeech: 'noun' },
  '休息': { definition: 'rest; to rest', partOfSpeech: 'verb/noun/verb' },
  '學習': { definition: 'to learn; to study', partOfSpeech: 'verb/noun/verb' },
  '學校': { definition: 'school', partOfSpeech: 'noun' },
  '學院': { definition: 'college; educational institute; school', partOfSpeech: 'noun' },
  '爺爺': { definition: '(coll.) father\'s father; paternal grandfather', partOfSpeech: 'noun' },
  '一半': { definition: 'half', partOfSpeech: 'measure word' },
  '一邊': { definition: 'one side; either side; on the one hand', partOfSpeech: 'd/f' },
  '一些': { definition: 'some; a few; a little', partOfSpeech: 'word' },
  '一樣': { definition: 'same; like; equal to', partOfSpeech: 'particle' },
  '醫生': { definition: 'doctor', partOfSpeech: 'noun' },
  '醫院': { definition: 'hospital', partOfSpeech: 'noun' },
  '有的': { definition: '(there are) some (who are...); some (exist)', partOfSpeech: 'd/pronoun' },
  '有時': { definition: 'sometimes; at times', partOfSpeech: 'word' },
  '有些': { definition: 'some; somewhat', partOfSpeech: 'pronoun' },
  '有意思': { definition: 'interesting; meaningful; enjoyable; fun', partOfSpeech: 'adjective' },
  '又是': { definition: '(once) again', partOfSpeech: 'word' },
  '右邊': { definition: 'right side; right', partOfSpeech: 'word' },
  '魚肉': { definition: 'fish (as food); (fig.) sb who is at the mercy of sb else', partOfSpeech: 'noun' },
  '運動': { definition: 'to move; to exercise; sports; movement; campaign', partOfSpeech: 'verb/noun/verb' },
  '在家': { definition: 'to be at home; (at a workplace) to be in (as opposed to being away on official business 出差)', partOfSpeech: 'verb' },
  '早飯': { definition: 'breakfast', partOfSpeech: 'noun' },
  '怎麼樣': { definition: 'how?; how about?; how was it?; how are things?', partOfSpeech: 'pronoun' },
  '站住': { definition: 'to stop; to halt; halt!; stop!', partOfSpeech: 'verb' },
  '丈夫': { definition: 'husband', partOfSpeech: 'noun' },
  '真的': { definition: 'really; truly; indeed', partOfSpeech: 'adjective' },
  '知識': { definition: 'knowledge; intellectual', partOfSpeech: 'noun/adjective' },
  '准備': { definition: 'to prepare; to get ready; preparation; preparatory', partOfSpeech: 'verb/noun/verb' },
  '桌子': { definition: 'table; desk', partOfSpeech: 'noun' },
  '自己': { definition: 'oneself; one\'s own', partOfSpeech: 'pronoun' },
  '走路': { definition: 'to walk', partOfSpeech: 'verb/noun/verb' },
  '嘴巴': { definition: 'mouth; slap in the face', partOfSpeech: 'noun' },
  '左邊': { definition: 'left; the left side; to the left of', partOfSpeech: 'word' },
  '作業': { definition: 'school assignment; homework; work; task; operation', partOfSpeech: 'noun' },
};

// HSK level estimation based on character complexity
function estimateHskLevel(word: string): number | undefined {
  // Common HSK 1-2 characters
  const hsk1 = '的一是不了在有这人我他她它们你您好吗呢很也都说看想要没用可以能会什么为因为所以';
  const hsk2 = '到里面上下来去给对为着从就能还让比跟向被';

  // Check if all characters are in basic sets
  const chars = [...word];
  const allBasic = chars.every(c => hsk1.includes(c) || hsk2.includes(c));

  if (allBasic && word.length <= 2) return 1;
  if (word.length === 1 && hsk1.includes(word)) return 1;
  if (word.length === 1 && hsk2.includes(word)) return 2;
  if (word.length <= 2) return 3;
  if (word.length <= 3) return 4;
  return 5;
}

// Check if character is punctuation
function isPunctuation(char: string): boolean {
  // Chinese and Western punctuation
  const chinesePunct = '\uff0c\u3002\uff01\uff1f\u3001\uff1b\uff1a\u201c\u201d\u2018\u2019\uff08\uff09\u3010\u3011\u300a\u300b\u2026\u2014\u00b7';
  const westernPunct = ',.!?;:\'"()-[]<>';
  return chinesePunct.includes(char) || westernPunct.includes(char);
}

/**
 * Segment Chinese text and add pinyin using proper word segmentation
 */
export function processChineseText(text: string): SegmentedWord[] {
  if (!text) return [];

  const words: SegmentedWord[] = [];
  let currentIndex = 0;

  // Use segment function to get proper word boundaries
  // segmentit: 3 = MinTokenization - groups characters into larger, more natural words
  // This helps with multi-character words like "神的" being kept together better
  const segments = segment(text, {
    toneType: 'symbol',
    segmentit: 3, // MinTokenization algorithm for better multi-character word grouping
  });

  for (const seg of segments) {
    const word = seg.origin;
    const wordPinyin = seg.result;
    const startIndex = currentIndex;
    const endIndex = currentIndex + word.length;
    currentIndex = endIndex;

    // Handle punctuation separately
    if (isPunctuation(word)) {
      words.push({
        chinese: word,
        pinyin: '',
        startIndex,
        endIndex,
      });
      continue;
    }

    // Look up word definition in our dictionary
    const wordDef = WORD_DEFINITIONS[word];

    words.push({
      chinese: word,
      pinyin: wordPinyin,
      definition: wordDef?.definition,
      partOfSpeech: wordDef?.partOfSpeech,
      hskLevel: estimateHskLevel(word),
      startIndex,
      endIndex,
    });
  }

  return words;
}

/**
 * Strip HTML tags from text
 */
function stripHtml(text: string): string {
  return text
    .replace(/<[^>]*>/g, '') // Remove HTML tags
    .replace(/&nbsp;/g, ' ') // Replace nbsp
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .trim();
}

/**
 * Convert API verse records to app Verse format
 */
export function convertApiVersesToChapter(records: FHLVerseRecord[]): Verse[] {
  return records.map((record) => {
    const cleanText = stripHtml(record.bible_text);
    return {
      number: record.sec,
      text: cleanText,
      words: processChineseText(cleanText),
    };
  });
}

/**
 * Process a single verse text
 */
export function processVerse(verseNumber: number, text: string): Verse {
  return {
    number: verseNumber,
    text,
    words: processChineseText(text),
  };
}
